export const groupTitleOptions = [
    { value: "MD", label: "MD-Sales" },
    { value: "RO", label: "RO-Sales" },
    { value: "CATALAN", label: "UA Sales" },
    { value: "FILIALE", label: "Filiale MD" },
    { value: "IndividualGroups", label: "Individual groups" },
    { value: "HR", label: "HR" },
    { value: "QUALITYDEPARTMENT", label: "Quality Department" },
    { value: "Marketing", label: "Marketing" },
    { value: "Agency", label: "Agency" },
    { value: "GreenCard", label: "Green Card" },
    { value: "FranchisePandaTur", label: "Panda Tur Franchise" },
    { value: "ORHEI", label: "Orhei Franchise MD" },
    { value: "CANTEMIR", label: "Cantemir Franchise MD" },
    { value: "EDINET", label: "Edinet Franchise MD" },
    { value: "DROCHIA", label: "Drochia Franchise MD" },
    { value: "IALOVENI", label: "Ialoveni Franchise MD" },
    { value: "BUIUCANI", label: "Chisinau, Buiucani Franchise MD" },
    { value: "CAUSENI", label: "Causeni Franchise MD" },
    { value: "SOLDANESTI", label: "Soldanesti Franchise MD" },
    { value: "REZINA", label: "Rezina Franchise MD" },
    { value: "RASCANI", label: "Chisinau, Riscani Franchise MD" },
    { value: "NISPORENI", label: "Nisporeni Franchise MD" },
    { value: "STAUCENI", label: "Stauceni Franchise MD" },
    { value: "HANCESTI", label: "Hincesti Franchise MD" },
    { value: "CIMISLIA", label: "Cimislia Franchise MD" },
    { value: "GLODENI", label: "Glodeni Franchise MD" },
    { value: "FranchiseCluj", label: "Cluj Franchise RO" },
    { value: "FranchiseTimisoara", label: "Timisoara Franchise RO" },
];