export const groupTitleOptions = [
    { value: "MD", label: "MD-Sales" },
    { value: "RO", label: "RO-Sales" },
    { value: "HR", label: "HR" },
    { value: "QUALITYDEPARTMENT", label: "Quality Department" },
    { value: "CATALAN", label: "UA Sales" },
    { value: "Filiale", label: "Filiale MD" },
    { value: "IndividualGroups", label: "Individual groups" },
    { value: "BusinessGroups", label: "Business groups" },
    { value: "Marketing", label: "Marketing" },
    { value: "Agency", label: "Agency" },
    { value: "GreenCard", label: "Green Card" },
    { value: "ORHEI", label: "Orhei Franchise" },
    { value: "CANTEMIR", label: "Cantemir Franchise" },
    { value: "EDINET", label: "Edinet Franchise" },
    { value: "DROCHIA", label: "Drochia Franchise" },
    { value: "IALOVENI", label: "Ialoveni Franchise" },
    { value: "BUIUCANI", label: "Chisinau, Buiucani Franchise" },
    { value: "CAUSENI", label: "Causeni Franchise" },
    { value: "SOLDANESTI", label: "Soldanesti Franchise" },
    { value: "REZINA", label: "Rezina Franchise" },
    { value: "RASCANI", label: "Chisinau, Riscani Franchise" },
    { value: "FranchiseTimisoara", label: "Timisoara Franchise" },
    { value: "NISPORENI", label: "Nisporeni Franchise" },
    { value: "FranchiseCluj", label: "Cluj Franchise" },
    { value: "STAUCENI", label: "Stauceni Franchise" },
    { value: "HANCESTI", label: "Hincesti Franchise" },
    { value: "CIMISLIA", label: "Cimislia Franchise" },
    { value: "FranchisePandaTur", label: "Panda Tur Franchise" },
    { value: "GLODENI", label: "Glodeni Franchise" },
];