export const marketingOptions = [
  "Egipt",
  "Turcia",
  "Dubai",
  "Munte Romania",
  "Munte Bulgaria",
  "Munte Bukovel",
  "Tratament",
  "Croaziere",
  "Excursii Europa",
  "Excursii Romania",
  "Excursii Moldova",
  "Cappadocia",
  "Excursie Istanbul (autocar)",
  "City Break de Vis în Istanbul",
  "TeamBuilding",
  "Munte Alpi (Austria, Italia, Elvetia, Franta)",
  "e-Visa UAE",
  "e-Visa Thailanda",
  "e-Visa India",
  "e-Visa Cuba",
  "e-Visa Kenya",
  "e-Visa Vietnam",
  "e-Visa Iordania",
  "e-Visa USA",
  "e-Visa China",
  "Green Card",
  "Delta Dunarii 3 zile cu All Inclusive",
  "Transalpina – Cazanele Dunarii – Chipul lui Decebal – Coloana Infinitului – Bran – Brasov",
  "Excursie Budapesta",
  "Excursii pentru elevi",
  "Excursii pentru profesori",
  "Excursii corporative",
  "Excursii pentru gradinite",
  "Grecia pentru toti",
  "Pelerinaj",
  "Athos",
  "Tabara Iuliana Beregoi 2025",
  "Targ de Craciun",
  "Bilete de avion",
  "Albania",
  "Bali",
  "Bulgaria",
  "Cipru",
  "Grecia avion",
  "Grecia autocar",
  "India",
  "Italia",
  "Laponia",
  "Maldive",
  "Mauritius",
  "Muntenegru",
  "R. Dominicana",
  "Spania",
  "Sri Lanka",
  "Thailanda",
  "Tunisia",
  "Zanzibar",
  "Exotica",
  "Altele",
  "Nu e specificat"
]