import { getLanguageByKey } from "../Components/utils/getLanguageByKey";

export const motivulRefuzuluiOptions = [
  "Clientul nu răspunde",
  "Prea scump",
  "Informații de referință",
  "Ne-a luat prea mult timp să răspundem la apeluri/mesaje",
  "Nevoia a dispărut",
  "Spam",
  "I-a ales pe alții",
  "Nu sunt mulțumiți de condiții",
  "Clientul nu răspunde (după 3 încercări de a suna)",
  "Mai scump decât concurenții",
  "Nu am găsit un tur potrivit",
  "Planuri schimbate / Nu a mers / Nu a zburat nicăieri",
  "A citit o mulțime de recenzii negative",
  "Turistul s-a îmbolnăvit",
  "Test pozitiv pentru Covid-19",
  "Client non-țintă",
  "Managerul nu cunoaște bine produsul / nu a oferit ceea ce este necesar",
  "Rezervări online",
  "Restituire",
  "Bani în depozit",
  "Concurs",
  "Concurs fotbal",
  "Rezultatul fuziunii tranzacțiilor",
  "Apel de intrare nesortat",
  "Apel rece",
  "Dublu",
  "Comentarii Facebook & Instagram",
  "Blocare Messenger",
  "RO Manager",
  "Departamentul de calitate",
  "Franciză",
  "Parteneriat",
  "Clienți corporate",
  "Trafic organic",
  "Reclamații",
  "Marketing",
  "Resurse umane",
  "Alt motiv",
].map((key) => getLanguageByKey(key));
