import { getLanguageByKey } from "../Components/utils/getLanguageByKey";
import { sortOptionsWithLastItems } from "./sortOptions";

const nameExcursionOptionKeys = [
  "Excursie de 4 zile la Istanbul cu Autocarul",
  "Conacul lui Manuc Bei + Ferma de Struți",
  "Excursie Cetatea Soroca – Cosăuți",
  "Excursie cu Vaporul + Saharna + Țipova + distracție cu DJ",
  "Mica Elveție Fetești – Zăbriceni",
  "Orheiul Vechi – Curchi – Satul Vatici",
  "Pădurea Domnească + Duruitoarea Veche + Costești-Stânca + Butești + Suta de Movile",
  "Plaiul Fagului",
  "Bucovina – Mocănița",
  "București + Therme București",
  "Cheile Bicazului – Lacul Roșu – Piatra Neamț",
  "Delta Dunării",
  "Excursie Brașov – Sinaia – Bran",
  "Excursie Cluj - Rimetea - Salina Turda - Târgul Mureș",
  "Excursie de 3 zile Transalpina – Cazanele Dunării – Chipul lui Decebal – Coloana Infinitului – Bran – Brașov / Transalpina – Brașov",
  "Ferma de Cerbi – Sibiu – Castelul de Lut – Brașov",
  "Iași + Shopping la Palas Mall",
  "Maramureș – Mocănița – Cascada Cailor",
  "Sibiu – Sighișoara",
  "Laponia",
  "Borsec-Fontana Spa & BiquadFilterNode",
  "Tabără la Munte cu Panda Tur și Iuliana Beregoi",
  "Transfăgărășan – Lacul Bîlea - Ferma de Cerbi – Sibiu – Catelul de Lut –Cetatea Făgăraș",
  "Transfăgărășan + Sighișoara + Lacul Bâlea",
  "Turul României – 6 orașe",
  "3 zile la mare la Costinești",
  "Bukovel + Rafting",
  "Viena – Salzburg",
  "Budapesta + Viena + Bratislava",
  "Circuit de 3 zile la Budapesta + Viena (Opțional)",
  "Circuit de 4 zile la Budapesta + Viena (Opțional)",
  "Crăciun în Viena-Salburg",
  "Grecia Low Cost / Excursie Grecia 8 zile 7 nopți",
  "Cracovia – Varșovia – Kosice",
  "Praga – Dresda – Karlovy Vary",
  "Turul Europei – 7 Orașe",
  "Turul în Europa – 5 Orașe",
  "Crăciun în Europa - 5 Orașe",
  "Țările Baltice – Polonia",
  "Turul Țărilor Balcanice",
  "Excursie Castelele din Bavaria + Austria",
  "BULGARIA - EXCURSIE DE 3 ZILE CU ALL INCLUSIVE",
  "EXCURSIE TURCIA-GEORGIA",
  "Pelerinaj în Israel",
  "Pelerinaj! Săptămâna Patimilor în Țara Sfântă: Întâmpinarea Luminii Sfinte",
  "Pelerinaj de o zi la 9 mănăstiri",
  "Pelerinaj la Muntele Athos, Tesalonic",
  "Pelerinaj la Părinții Arsenie Boca și Iustin Pârvu",
  "Pelerinaj de 2 zile la Sf. Parascheva şi Mănăstirile din Iaşi",
  "Pelerinaj de 2 zile la Mănăstirile din Neamț",
  "Pelerinaj de 2 zile la Putna și Mănăstirile din Bucovina",
  "Munte Bulgaria",
  "Munte România",
  "Mare Bulgaria",
  "Mare Grecia",
  "Mare Dubai",
  "Mare Egipt",
  "Mare Maldive",
  "Mare Turcia",
  "Mare Zanzibar",
  "Canary Islands",
  "Exotic Tanzania",
  "Exotic Thailand",
  "Croaziera",
  "Citybreak",
  "Tratament",
  "Alte"
];

export const nameExcursionOptions = sortOptionsWithLastItems(
  nameExcursionOptionKeys.map((key) => ({
    value: key,
    label: getLanguageByKey(key) || key,
  }))
);
